### ISSUE TITLE
样式太丑了，能不能改下css

### ISSUE THREAD

**Issue by FunkySamuel37** [sciooga/Keyboard-launch#4]
http://codepen.io/jakealbaugh/pen/LNdWZG
这个就挺不错的

**Comment by sciooga** [comment]
我看见你有 fork ，不如你尝试下？

**Comment by FunkySamuel37** [comment]
我不会做chrome插件啊－ －

**Comment by sciooga** [comment]
改样式并不需要用到 Chrome 扩展的 API 啊... 就是改改 css 而已。

**Comment by FunkySamuel37** [comment]
![image](https://cloud.githubusercontent.com/assets/11454137/14774281/295900f8-0ae7-11e6-9e89-fdd45eb27f0d.png)
好像ext目录下的版本更新吧

**Comment by sciooga** [comment]
web 是网页版，ext 是扩展版，但是两部分用的 css 是相同的都是 launch.css，两个文件夹内都有这个文件。
